CREATE TABLE [dbo].[tblCONV_ReleveDeCompte_RecensementPCEEerreurL] (
    [RecuArgentEnsuite]                  VARCHAR (1)               NOT NULL,
    [BeneficiaryID]                      [dbo].[MoID]              NOT NULL,
    [NomBeneficiaire]                    [dbo].[MoLastNameoption]  NULL,
    [PrenomBeneficiaire]                 [dbo].[MoFirstNameoption] NULL,
    [DateNaissanceBenef]                 [dbo].[MoDateoption]      NULL,
    [NomSouscripteur]                    [dbo].[MoLastNameoption]  NULL,
    [PrenomSouscripteur]                 [dbo].[MoFirstNameoption] NULL,
    [SubscriberID]                       [dbo].[MoID]              NOT NULL,
    [SexID]                              [dbo].[MoSex]             NOT NULL,
    [LongSexName]                        [dbo].[MoDescoption]      NULL,
    [ShortSexName]                       [dbo].[MoDescoption]      NULL,
    [LangID]                             [dbo].[MoLang]            NOT NULL,
    [Address]                            VARCHAR (527)             NULL,
    [City]                               [dbo].[MoCity]            NULL,
    [StateName]                          [dbo].[MoDescoption]      NULL,
    [CountryID]                          CHAR (4)                  NULL,
    [CodePostal]                         VARCHAR (10)              NULL,
    [ConventionNo]                       VARCHAR (15)              NOT NULL,
    [V1_ConventionStateID]               [dbo].[MoOptionCode]      NULL,
    [V2_ConventionStateID]               [dbo].[MoOptionCode]      NULL,
    [vcPCGLastName]                      VARCHAR (50)              NULL,
    [vcPCGFirstName]                     VARCHAR (40)              NULL,
    [vcPCGSINorEN]                       VARCHAR (15)              NULL,
    [RelationBeneficiaireVSSouscripteur] VARCHAR (25)              NOT NULL,
    [NomRep]                             [dbo].[MoLastNameoption]  NULL,
    [PrenomRep]                          [dbo].[MoFirstNameoption] NULL
);

