CREATE TABLE [dbo].[tblTEMP_DepenseDeCommissionParUnite] (
    [Sort]                     INT            NOT NULL,
    [DateDebut]                DATE           NULL,
    [DateFin]                  DATE           NULL,
    [UnitID]                   INT            NOT NULL,
    [ConventionNo]             VARCHAR (15)   NOT NULL,
    [RepID]                    INT            NOT NULL,
    [RepcodeINT]               INT            NULL,
    [RepName]                  VARCHAR (86)   NULL,
    [RepRoleDesc]              VARCHAR (75)   NOT NULL,
    [LevelShortDesc]           VARCHAR (75)   NULL,
    [RoleNiveau]               VARCHAR (151)  NULL,
    [DateDebutOperFIN]         DATE           NULL,
    [TauxDeRemun]              VARCHAR (8000) NULL,
    [TotalFee]                 VARCHAR (8000) NULL,
    [VariationQteUnite]        VARCHAR (8000) NULL,
    [QteUniteFin]              VARCHAR (8000) NULL,
    [UniteSurRepresentant]     VARCHAR (8000) NULL,
    [AvACouvrir]               VARCHAR (8000) NULL,
    [Avances]                  VARCHAR (8000) NULL,
    [AvCouv]                   VARCHAR (8000) NULL,
    [AvResil]                  VARCHAR (8000) NULL,
    [AvSpecial]                VARCHAR (8000) NULL,
    [AvTotal]                  VARCHAR (8000) NULL,
    [Commission]               VARCHAR (8000) NULL,
    [Boni]                     VARCHAR (8000) NULL,
    [BoniConAju]               VARCHAR (8000) NULL,
    [Retenu]                   VARCHAR (8000) NULL,
    [FuturCom_Sommaire]        VARCHAR (8000) NULL,
    [FuturCOM_CT]              VARCHAR (8000) NULL,
    [FuturCOM_LT]              VARCHAR (8000) NULL,
    [FuturCOM_CT_LT]           VARCHAR (8000) NULL,
    [EcartFuturCom]            VARCHAR (8000) NULL,
    [FuturCOM_CT_LT_31DecPrec] VARCHAR (8000) NULL,
    [RepriseCOMsurNSF]         VARCHAR (8000) NULL,
    [RepriseAVANCEsurNSF]      VARCHAR (8000) NULL,
    [NoteTFR]                  VARCHAR (3)    NULL,
    [TFR]                      VARCHAR (8000) NULL,
    [DateFinCT]                DATE           NULL
);

