CREATE TABLE [dbo].[tblTEMP_SuiviRep] (
    [repid]             INT           NULL,
    [repcode]           VARCHAR (75)  NULL,
    [firstname]         VARCHAR (35)  NULL,
    [lastname]          VARCHAR (35)  NULL,
    [DIRfirstname]      VARCHAR (35)  NULL,
    [DIRlastname]       VARCHAR (35)  NULL,
    [businessstart]     DATETIME      NULL,
    [FirstDateSale]     DATETIME      NULL,
    [NbMois]            INT           NULL,
    [RepVille]          VARCHAR (100) NULL,
    [CM0]               FLOAT (53)    NULL,
    [CM1]               FLOAT (53)    NULL,
    [RM1]               FLOAT (53)    NULL,
    [CM2]               FLOAT (53)    NULL,
    [RM2]               FLOAT (53)    NULL,
    [CM3]               FLOAT (53)    NULL,
    [RM3]               FLOAT (53)    NULL,
    [CM4]               FLOAT (53)    NULL,
    [RM4]               FLOAT (53)    NULL,
    [CM5]               FLOAT (53)    NULL,
    [RM5]               FLOAT (53)    NULL,
    [CM6]               FLOAT (53)    NULL,
    [RM6]               FLOAT (53)    NULL,
    [CM7]               FLOAT (53)    NULL,
    [RM7]               FLOAT (53)    NULL,
    [CM8]               FLOAT (53)    NULL,
    [RM8]               FLOAT (53)    NULL,
    [CM9]               FLOAT (53)    NULL,
    [RM9]               FLOAT (53)    NULL,
    [CM10]              FLOAT (53)    NULL,
    [RM10]              FLOAT (53)    NULL,
    [CM11]              FLOAT (53)    NULL,
    [RM11]              FLOAT (53)    NULL,
    [CM12]              FLOAT (53)    NULL,
    [RM12]              FLOAT (53)    NULL,
    [YearBrut]          FLOAT (53)    NULL,
    [YearRetrait]       FLOAT (53)    NULL,
    [YearReinsc]        FLOAT (53)    NULL,
    [YearNet]           FLOAT (53)    NULL,
    [YearAvgRetrait]    FLOAT (53)    NULL,
    [Month24Brut]       FLOAT (53)    NULL,
    [Month24Retrait]    FLOAT (53)    NULL,
    [Month24Reinsc]     FLOAT (53)    NULL,
    [Month24Net]        FLOAT (53)    NULL,
    [Month24AvgRetrait] FLOAT (53)    NULL,
    [DiffCons]          FLOAT (53)    NULL,
    [NM1]               FLOAT (53)    NULL,
    [NMUniv1]           FLOAT (53)    NULL,
    [NMRflex1]          FLOAT (53)    NULL,
    [NM2]               FLOAT (53)    NULL,
    [NMUniv2]           FLOAT (53)    NULL,
    [NMRflex2]          FLOAT (53)    NULL,
    [NM3]               FLOAT (53)    NULL,
    [NMUniv3]           FLOAT (53)    NULL,
    [NMRflex3]          FLOAT (53)    NULL,
    [NM4]               FLOAT (53)    NULL,
    [NMUniv4]           FLOAT (53)    NULL,
    [NMRflex4]          FLOAT (53)    NULL,
    [NM5]               FLOAT (53)    NULL,
    [NMUniv5]           FLOAT (53)    NULL,
    [NMRflex5]          FLOAT (53)    NULL,
    [NM6]               FLOAT (53)    NULL,
    [NMUniv6]           FLOAT (53)    NULL,
    [NMRflex6]          FLOAT (53)    NULL,
    [NM7]               FLOAT (53)    NULL,
    [NMUniv7]           FLOAT (53)    NULL,
    [NMRflex7]          FLOAT (53)    NULL,
    [NM8]               FLOAT (53)    NULL,
    [NMUniv8]           FLOAT (53)    NULL,
    [NMRflex8]          FLOAT (53)    NULL,
    [NM9]               FLOAT (53)    NULL,
    [NMUniv9]           FLOAT (53)    NULL,
    [NMRflex9]          FLOAT (53)    NULL,
    [NM10]              FLOAT (53)    NULL,
    [NMUniv10]          FLOAT (53)    NULL,
    [NMRflex10]         FLOAT (53)    NULL,
    [NM11]              FLOAT (53)    NULL,
    [NMUniv11]          FLOAT (53)    NULL,
    [NMRflex11]         FLOAT (53)    NULL,
    [NM12]              FLOAT (53)    NULL,
    [NMUniv12]          FLOAT (53)    NULL,
    [NMRflex12]         FLOAT (53)    NULL,
    [moisLastPctUniv]   FLOAT (53)    NULL,
    [moisLastPctRflex]  FLOAT (53)    NULL,
    [mois3]             FLOAT (53)    NULL,
    [mois3PctUniv]      FLOAT (53)    NULL,
    [mois3PctRflex]     FLOAT (53)    NULL,
    [mois3Resil]        FLOAT (53)    NULL,
    [mois6]             FLOAT (53)    NULL,
    [mois6PctUniv]      FLOAT (53)    NULL,
    [mois6PctRflex]     FLOAT (53)    NULL,
    [mois6Resil]        FLOAT (53)    NULL,
    [mois12]            FLOAT (53)    NULL,
    [mois12PctUniv]     FLOAT (53)    NULL,
    [mois12PctRflex]    FLOAT (53)    NULL,
    [mois12Resil]       FLOAT (53)    NULL,
    [AVGmois]           FLOAT (53)    NULL
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Table temporaire utilisé pour le rapport statistique des ventes et taux de conservation des 12 dernier mois (GU_RP_SuiviRep)', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tblTEMP_SuiviRep';

