CREATE TABLE [dbo].[TblTEMP_ARIconvRIOetTRI] (
    [OperTypeID]                CHAR (3)     NOT NULL,
    [conventionno]              VARCHAR (15) NOT NULL,
    [ConventionStateID]         CHAR (3)     NOT NULL,
    [ContientCapitalsubvention] INT          NOT NULL,
    [SCEE]                      MONEY        NOT NULL,
    [RendSCEE]                  MONEY        NOT NULL,
    [RendSCEE_TIN]              MONEY        NOT NULL,
    [SCEEPlus]                  MONEY        NOT NULL,
    [RendSCEEPlus]              MONEY        NOT NULL,
    [BEC]                       MONEY        NOT NULL,
    [RendBEC]                   MONEY        NOT NULL,
    [IQEE]                      MONEY        NOT NULL,
    [RendIQEE]                  MONEY        NULL,
    [RendIQEE_TIN]              MONEY        NOT NULL,
    [RendSurInteretRecuRQ]      MONEY        NOT NULL,
    [IQEEPlus]                  MONEY        NOT NULL,
    [RendIQEEPlus]              MONEY        NOT NULL,
    [RendMontantsouscrit]       MONEY        NOT NULL,
    [RendTIN]                   MONEY        NOT NULL,
    [INM_c]                     MONEY        NULL,
    [ITR_c]                     MONEY        NULL,
    [INS_c]                     MONEY        NULL,
    [ISPlus_c]                  MONEY        NULL,
    [IBC_c]                     MONEY        NULL,
    [IST_c]                     MONEY        NULL,
    [MIM_c]                     MONEY        NULL,
    [ICQ_c]                     MONEY        NULL,
    [IMQ_c]                     MONEY        NULL,
    [III_c]                     MONEY        NULL,
    [IIQ_c]                     MONEY        NULL,
    [IQI_c]                     MONEY        NULL,
    [EAFB_c]                    MONEY        NULL
);

