
CREATE FUNCTION dbo.fn_Un_SCEEMoneyToString
( @FAmount       MoMoney
)
RETURNS VARCHAR(9)
AS
BEGIN
  RETURN(SUBSTRING('000000000',1,9-LEN(CAST(CAST(FLOOR(ABS(@FAmount) * 100) AS INTEGER) AS VARCHAR(9))))+CAST(CAST(FLOOR(ABS(@FAmount) * 100) AS INTEGER) AS VARCHAR(9)))
END

